using UnityEngine.UIElements;

namespace UnityEssentials
{
    public enum UIElementType
    {
        None,
        VisualElement,
        BindableElement,
        Button,
        Label,
        Scroller,
        TextField,
        Foldout,
        Slider,
        SliderInt,
        ProgressBar,
        DropdownField,
        TextElement,
        ScrollView,
        Toggle,
        RadioButton,
        Toolbar,
        ToolbarButton,
        ToolbarToggle,
        ToolbarSpacer,
        ToolbarMenu,
        ListView,
        MultiColumnListView,
        IMGUIContainer,
        Image,
        Box,
        GroupBox,
        HelpBox,
        MinMaxSlider,
        EnumField,
        IntegerField,
        FloatField,
        LongField,
        DoubleField,
        Vector2Field,
        Vector3Field,
        Vector4Field,
        ColorField,
        RectField,
        BoundsField,
        MaskField,
        PropertyField,
        InspectorElement,
    }

    public static class UIElementTypes
    {
        public static System.Type GetElementType(UIElementType type) =>
            type switch
            {
                UIElementType.VisualElement => typeof(VisualElement),
                UIElementType.BindableElement => typeof(BindableElement),
                UIElementType.Button => typeof(Button),
                UIElementType.Label => typeof(Label),
                UIElementType.Scroller => typeof(Scroller),
                UIElementType.TextField => typeof(TextField),
                UIElementType.Foldout => typeof(Foldout),
                UIElementType.Slider => typeof(Slider),
                UIElementType.SliderInt => typeof(SliderInt),
                UIElementType.ProgressBar => typeof(ProgressBar),
                UIElementType.DropdownField => typeof(DropdownField),
                UIElementType.TextElement => typeof(TextElement),
                UIElementType.ScrollView => typeof(ScrollView),
                UIElementType.Toggle => typeof(Toggle),
                UIElementType.RadioButton => typeof(RadioButton),
                UIElementType.ListView => typeof(ListView),
                UIElementType.MultiColumnListView => typeof(MultiColumnListView),
                UIElementType.IMGUIContainer => typeof(IMGUIContainer),
                UIElementType.Image => typeof(Image),
                UIElementType.Box => typeof(Box),
                UIElementType.GroupBox => typeof(GroupBox),
                UIElementType.HelpBox => typeof(HelpBox),
                UIElementType.MinMaxSlider => typeof(MinMaxSlider),
                UIElementType.EnumField => typeof(EnumField),
                UIElementType.IntegerField => typeof(IntegerField),
                UIElementType.FloatField => typeof(FloatField),
                UIElementType.LongField => typeof(LongField),
                UIElementType.DoubleField => typeof(DoubleField),
                UIElementType.Vector2Field => typeof(Vector2Field),
                UIElementType.Vector3Field => typeof(Vector3Field),
                UIElementType.Vector4Field => typeof(Vector4Field),
                UIElementType.RectField => typeof(RectField),
                UIElementType.BoundsField => typeof(BoundsField),
                _ => null,
            };

        public static UIElementType GetElementType(this VisualElement element) =>
            element switch
            {
                Button => UIElementType.Button,
                Label => UIElementType.Label,
                Scroller => UIElementType.Scroller,
                TextField => UIElementType.TextField,
                Foldout => UIElementType.Foldout,
                Slider => UIElementType.Slider,
                SliderInt => UIElementType.SliderInt,
                ProgressBar => UIElementType.ProgressBar,
                DropdownField => UIElementType.DropdownField,
                TextElement => UIElementType.TextElement,
                ScrollView => UIElementType.ScrollView,
                Toggle => UIElementType.Toggle,
                RadioButton => UIElementType.RadioButton,
                ListView => UIElementType.ListView,
                MultiColumnListView => UIElementType.MultiColumnListView,
                IMGUIContainer => UIElementType.IMGUIContainer,
                Image => UIElementType.Image,
                Box => UIElementType.Box,
                GroupBox => UIElementType.GroupBox,
                HelpBox => UIElementType.HelpBox,
                MinMaxSlider => UIElementType.MinMaxSlider,
                EnumField => UIElementType.EnumField,
                IntegerField => UIElementType.IntegerField,
                FloatField => UIElementType.FloatField,
                LongField => UIElementType.LongField,
                DoubleField => UIElementType.DoubleField,
                Vector2Field => UIElementType.Vector2Field,
                Vector3Field => UIElementType.Vector3Field,
                Vector4Field => UIElementType.Vector4Field,
                RectField => UIElementType.RectField,
                BoundsField => UIElementType.BoundsField,
                _ => UIElementType.VisualElement
            };
    }
}